config/routes.rb
Rails.application.routes.draw do
  resources :charges
  devise_for :users

  root 'welcome#index'
    get  'about'    => 'welcome#about'
    get  'home'    => 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 500

    Stripe.api_key = "sk_test_CMjoP9UHYwPP7LHh54Gj1HJ3"

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$25.00</strong>!</h2>

app/views/charges/new.html.erb
<script type="text/javascript">
  Stripe.setPublishableKey('pk_test_1cIpyYxoMDj81Sh5ogahxydo');
</script>


<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KEM Foundation Inc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
</head>
<body>
  <%= render 'shared/header' %>
  <%= render 'shared/slider' %>
  <div id="fh5co-main">
<%= yield %>
</div>
  	<footer id="fh5co-footer">

  		<div class="container">
  			<div class="row">
  				<div class="col-md-6 col-sm-6">
  					<div class="fh5co-footer-widget">
  						<h2 class="fh5co-footer-logo">Booster</h2>
  						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
  					</div>
  					<div class="fh5co-footer-widget">
  						<ul class="fh5co-social">
  							<li><a href="#"><i class="icon-facebook"></i></a></li>
  							<li><a href="#"><i class="icon-twitter"></i></a></li>
  							<li><a href="#"><i class="icon-instagram"></i></a></li>
  							<li><a href="#"><i class="icon-linkedin"></i></a></li>
  							<li><a href="#"><i class="icon-youtube"></i></a></li>
  						</ul>
  					</div>
  				</div>

  				<div class="col-md-2 col-sm-6">
  					<div class="fh5co-footer-widget top-level">
  						<h4 class="fh5co-footer-lead ">Company</h4>
  						<ul>
  							<li><a href="#">About</a></li>
  							<li><a href="#">Contact</a></li>
  							<li><a href="#">News</a></li>
  							<li><a href="#">Support</a></li>
  							<li><a href="#">Career</a></li>
  						</ul>
  					</div>
  				</div>

  				<div class="visible-sm-block clearfix"></div>

  				<div class="col-md-2 col-sm-6">
  					<div class="fh5co-footer-widget top-level">
  						<h4 class="fh5co-footer-lead">Features</h4>
  						<ul class="fh5co-list-check">
  							<li><a href="#">Lorem ipsum dolor.</a></li>
  							<li><a href="#">Ipsum mollitia dolore.</a></li>
  							<li><a href="#">Eius similique in.</a></li>
  							<li><a href="#">Aspernatur similique nesciunt.</a></li>
  							<li><a href="#">Laboriosam ad commodi.</a></li>
  						</ul>
  					</div>
  				</div>
  				<div class="col-md-2 col-sm-6">
  					<div class="fh5co-footer-widget top-level">
  						<h4 class="fh5co-footer-lead ">Products</h4>
  						<ul class="fh5co-list-check">
  							<li><a href="#">Lorem ipsum dolor.</a></li>
  							<li><a href="#">Ipsum mollitia dolore.</a></li>
  							<li><a href="#">Eius similique in.</a></li>
  							<li><a href="#">Aspernatur similique nesciunt.</a></li>
  							<li><a href="#">Laboriosam ad commodi.</a></li>
  						</ul>
  					</div>
  				</div>
  			</div>

  			<div class="row fh5co-row-padded fh5co-copyright">
  				<div class="col-md-5">
  					<p><small>&copy; Booster Free HTML5 Template. All Rights Reserved. <br>Designed by: <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> | Images by: <a href="http://deathtothestockphoto.com/" target="_blank">DeathToTheStockPhoto</a> </small></p>
  				</div>
  			</div>
  		</div>

  	</footer>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<header id="fh5co-header" role="banner">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
        <!-- Mobile Toggle Menu Button -->
        <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle" data-toggle="collapse" data-target="#fh5co-navbar" aria-expanded="false" aria-controls="navbar"><i></i></a>
        <%= link_to 'KEM Foundation', root_path, class:'navbar-brand' %>
        </div>
        <div id="fh5co-navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if current_page?(root_path) %>
              <li class="active">
            <% else %>
              <li>
            <% end %>
              <%= link_to root_path do %><span>
                home
                <span class="border"></span></span>
              <% end %>
            </li>
            <% if signed_in? %>
                <li><%= link_to destroy_user_session_path, :method => :delete do %><span>
                  Logout
                  <span class="border"></span></span>
                </li>
              <% end %>
              <% if current_page?(edit_user_registration_path) %>
                <li class="active">
              <% else %>
                <li>
              <% end %>
              <%= link_to edit_user_registration_path do %><span>
                Account
                <span class="border"></span></span>
              </li>
              <% end %>
            <% else %>
            <li>
              <%= link_to new_user_session_path do %>
                <span>Log In <span class="border"></span></span>
              <% end %>
              </li>
              <% if current_page?(new_user_registration_path) %>
                <li class="active">
              <% else %>
                <li>
              <% end %>
              <%= link_to new_user_registration_path do %><span>
                Sign Up
                <span class="border"></span></span>
              </li>
              <% end %>
            <% end %>
            <% if current_page?(about_path) %>
              <li class="active">
            <% else %>
              <li>
            <% end %>
              <%= link_to about_path do %><span>
                About Us
                <span class="border"></span></span>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <!-- END .header -->

app/views/shared/_slider.html.erb
<div class="fh5co-slider">
  <div class="owl-carousel owl-carousel-fullwidth">
      <div class="item" style="background-image:url(http://meds.queensu.ca/blog/wp-content/uploads/2013/02/making-waves2.png)">
        <div class="fh5co-overlay"></div>
        <div class="container">
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <div class="fh5co-owl-text-wrap">
                <div class="fh5co-owl-text text-center to-animate">
                  <h1 class="fh5co-lead">KEm Foundation</h1>
                <h2 class="fh5co-sub-lead">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco<a href="#">KEM FoundationHTML5.co</a></h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="item" style="background-image:url(http://i.embed.ly/1/display/resize?key=1e6a1a1efdb011df84894040444cdc60&url=http%3A%2F%2Fi.huffpost.com%2Fgen%2F2876862%2Fimages%2Fo-SUPERHERO-facebook.jpg)">
        <div class="fh5co-overlay"></div>
        <div class="container">
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <div class="fh5co-owl-text-wrap">
                <div class="fh5co-owl-text text-center to-animate">
                  <h1 class="fh5co-lead">KEM Foundation</h1>
                <h2 class="fh5co-sub-lead">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco <a href="#">KEM Foundation.co</a></h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="item" style="background-image:url(http://miracleleaguelouisville.org/wp-content/uploads/2014/08/miraclereds.jpg)">
        <div class="fh5co-overlay"></div>
        <div class="container">
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <div class="fh5co-owl-text-wrap">
                <div class="fh5co-owl-text text-center to-animate">
                  <h1 class="fh5co-lead">KEM Foundation</h1>
                <h2 class="fh5co-sub-lead">KEM Foundation "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco <a href="#">KEM Foundation.co</a></h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="item" style="background-image:url(http://media.nj.com/gloucester-photos/photo/2012/05/-4d83661c6ac17d82.JPG)">
        <div class="fh5co-overlay"></div>
        <div class="container">
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <div class="fh5co-owl-text-wrap">
                <div class="fh5co-owl-text text-center to-animate">
                  <h1 class="fh5co-lead">Kem Foundation</h1>
                <h2 class="fh5co-sub-lead">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco <a href="#">KEM Foundation.co</a></h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/welcome/about.html.erb
<aside class="fh5co-page-heading">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h1 class="fh5co-page-heading-lead">
						About Us
						<span class="fh5co-border"></span>
					</h1>

				</div>
			</div>
		</div>
	</aside>

	<div id="fh5co-main">

		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-push-4">
					<h1>Header Level 1</h1>

					<p><strong>Our goal</strong> is to bridge the gap for special needs induviduals through fundamental life learning skills and education
					<h2>Header Level 2</h2>

					<ol>
					   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
					   <li>Aliquam tincidunt mauris eu risus.</li>
					</ol>

					<blockquote><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus magna. Cras in mi at felis aliquet congue. Ut a est eget ligula molestie gravida. Curabitur massa. Donec eleifend, libero at sagittis mollis, tellus est malesuada tellus, at luctus turpis elit sit amet quam. Vivamus pretium ornare est.</p></blockquote>

					<h3>Header Level 3</h3>

					<ul>
					   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
					   <li>Aliquam tincidunt mauris eu risus.</li>
					</ul>

<pre><code>#header h1 a {
display: block;
width: 300px;
height: 80px;
}
</code></pre>
					<h2>Buttons</h2>
					<a href="#" class="btn btn-primary">I'm a button</a>
					<a href="#" class="btn btn-outline">Button outline</a>

					<div class="row">
						<form action="#" method="post">
							<div class="col-md-6">
								<div class="form-group">
									<label for="name" class="sr-only">Email</label>
									<input placeholder="Name" id="name" type="text" class="form-control input-lg">
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="email" class="sr-only">Email</label>
									<input placeholder="Email" id="email" type="text" class="form-control input-lg">
								</div>
							</div>
							<div class="col-md-12">
								<div class="form-group">
									<label for="gender" class="sr-only">Gender</label>
									<select class="form-control input-lg" id="gender">
									  <option>--Gender--</option>
									  <option>Male</option>
									  <option>Female</option>
									</select>
								</div>
							</div>
							<div class="col-md-12">
								<div class="form-group">
									<label for="message" class="sr-only">Message</label>
									<textarea placeholder="Message" id="message" class="form-control input-lg" rows="3"></textarea>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<input type="submit" class="btn btn-primary " value="Send">

									<input type="reset" class="btn btn-outline  " value="Reset">
								</div>
							</div>
						</form>
					</div>

					<h2>Image alignment</h2>

					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi, asperiores, hic. Nihil, fugit. Illo maxime nemo minus magnam recusandae, ab culpa dignissimos velit. Consequatur voluptate, veniam ad ea asperiores sequi culpa, distinctio qui voluptates enim, fugit sint architecto rerum numquam deleniti incidunt ipsa omnis soluta similique quaerat deserunt provident repellendus excepturi! Alias natus dicta quasi hic obcaecati, pariatur eaque enim suscipit exercitationem quo libero eveniet aliquam repudiandae, nobis, quos tenetur ipsa quia eligendi expedita beatae laboriosam non molestias rem. Totam, aspernatur qui eos harum iusto reprehenderit corporis similique. Corporis delectus ullam earum sint in cum repellat laborum error et dolorum.
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi ipsam, sint voluptas esse quaerat modi, ex minus provident est consectetur facilis enim vitae, cupiditate deleniti numquam illo labore maiores fuga dolorum. Quae tempora hic, dolorum possimus porro sapiente! Exercitationem velit harum, assumenda deserunt minus dolorem atque illo? Repudiandae atque, magni. Lorem ipsum dolor sit amet, consectetur adipisicing elit. At sequi doloremque ullam consequuntur saepe eaque magnam incidunt eligendi inventore unde quaerat mollitia, delectus, autem blanditiis modi beatae accusantium sapiente aperiam, praesentium odit. Eum quos, quas quasi quae repudiandae, velit et facere explicabo excepturi eaque sint tempore distinctio suscipit aspernatur nostrum reiciendis accusantium tenetur. Tempora enim consequuntur eos? Provident, at, obcaecati doloremque exercitationem hic autem est veritatis, voluptatum quos ad voluptatem similique sint nam corporis. Quia minus numquam tempora officiis, quo corrupti tempore natus sequi placeat. Quibusdam veniam nesciunt modi doloribus sapiente rerum perspiciatis praesentium esse dicta, magnam quaerat, sit optio!</p>

					<img src="images/img_small_2.jpg" alt="FREEHTML5.co Free HTML5 Bootstrap template" class="fh5co-align-right img-responsive">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi, asperiores, hic. Nihil, fugit. Illo maxime nemo minus magnam recusandae, ab culpa dignissimos velit. Consequatur voluptate, veniam ad ea asperiores sequi culpa, distinctio qui voluptates enim, fugit sint architecto rerum numquam deleniti incidunt ipsa omnis soluta similique quaerat deserunt provident repellendus excepturi! Alias natus dicta quasi hic obcaecati, pariatur eaque enim suscipit exercitationem quo libero eveniet aliquam repudiandae, nobis, quos tenetur ipsa quia eligendi expedita beatae laboriosam non molestias rem. Totam, aspernatur qui eos harum iusto reprehenderit corporis similique. Corporis delectus ullam earum sint in cum repellat laborum error et dolorum.
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi ipsam, sint voluptas esse quaerat modi, ex minus provident est consectetur facilis enim vitae, cupiditate deleniti numquam illo labore maiores fuga dolorum. Quae tempora hic, dolorum possimus porro sapiente! Exercitationem velit harum, assumenda deserunt minus dolorem atque illo? Repudiandae atque, magni. Lorem ipsum dolor sit amet, consectetur adipisicing elit. At sequi doloremque ullam consequuntur saepe eaque magnam incidunt eligendi inventore unde quaerat mollitia, delectus, autem blanditiis modi beatae accusantium sapiente aperiam, praesentium odit. Eum quos, quas quasi quae repudiandae, velit et facere explicabo excepturi eaque sint tempore distinctio suscipit aspernatur nostrum reiciendis accusantium tenetur. Tempora enim consequuntur eos? Provident, at, obcaecati doloremque exercitationem hic autem est veritatis, voluptatum quos ad voluptatem similique sint nam corporis. Quia minus numquam tempora officiis, quo corrupti tempore natus sequi placeat. Quibusdam veniam nesciunt modi doloribus sapiente rerum perspiciatis praesentium esse dicta, magnam quaerat, sit optio!</p>




				</div>



				<div class="col-md-4 col-md-pull-8">

					<div class="fh5co-sidebox">
						<h3 class="fh5co-sidebox-lead">Image List</h3>
						<ul class="fh5co-post">
							<li>
								<a href="#">
									<div class="fh5co-post-media"><img src="assets/slide_1.jpg" alt="FREEHTML5.co Free HTML5 Template"></div>
									<div class="fh5co-post-blurb">
										Lorem ipsum dolor sit amet, consectetur adipisicing elit.
										<span class="fh5co-post-meta">Oct. 12, 2015</span>
									</div>
								</a>
							</li>
							<li>
								<a href="#">
									<div class="fh5co-post-media"><img src="assets/slide_2.jpg" alt="FREEHTML5.co Free HTML5 Template"></div>
									<div class="fh5co-post-blurb">
										Lorem ipsum dolor sit amet, consectetur adipisicing elit.
										<span class="fh5co-post-meta">Oct. 12, 2015</span>
									</div>
								</a>
							</li>
							<li>
								<a href="#">
									<div class="fh5co-post-media"><img src="assets/slide_3.jpg" alt="FREEHTML5.co Free HTML5 Template"></div>
									<div class="fh5co-post-blurb">
										Lorem ipsum dolor sit amet, consectetur adipisicing elit.
										<span class="fh5co-post-meta">Oct. 12, 2015</span>
									</div>
								</a>
							</li>
						</ul>

					</div>

					<div class="fh5co-sidebox">
						<h3 class="fh5co-sidebox-lead">Paragraph</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, temporibus vitae. Dolores sequi, animi dolorem. Ullam minima laudantium culpa dolorem, nulla doloribus totam obcaecati reprehenderit quasi nam eius autem nihil.</p>
					</div>

					<div class="fh5co-sidebox">
						<h3 class="fh5co-sidebox-lead">Check list</h3>
						<ul class="fh5co-list-check">
							<li>Lorem ipsum dolor sit.</li>
							<li>Nostrum eveniet animi sint.</li>
							<li>Dolore eligendi, porro ipsam.</li>
							<li>Repudiandae voluptate dolorem voluptas.</li>
							<li>Voluptate cupiditate, est laborum?</li>
						</ul>
					</div>
				</div>

			</div>
		</div>
	</div>

app/views/welcome/index.html.erb
<div id="fh5co-main">
  <!-- Features -->

  <div id="fh5co-features">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-8 col-md-offset-2">
          <h2 class="fh5co-section-lead">Key Features</h2>
          <h3 class="fh5co-section-sub-lead">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</h3>
        </div>
        <div class="fh5co-spacer fh5co-spacer-md"></div>
      </div>
      <div class="row">
        <div class="col-md-6 col-sm-6 fh5co-feature-border">
          <div class="fh5co-feature">
            <div class="fh5co-feature-icon to-animate">
              <i class="icon-bag"></i>
            </div>
            <div class="fh5co-feature-text">
              <h3>Shopping Bag</h3>
              <p>Far far away, behind the word mountains, far from the countries Vokalia.</p>
              <p><a href="#">Read more</a></p>
            </div>
          </div>
          <div class="fh5co-feature no-border">
            <div class="fh5co-feature-icon to-animate">
              <i class="icon-head"></i>
            </div>
            <div class="fh5co-feature-text">
              <h3>User Satisfaction</h3>
              <p>Far far away, behind the word mountains, far from the countries Vokalia.</p>
              <p><a href="#">Read more</a></p>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-sm-6">
          <div class="fh5co-feature">
            <div class="fh5co-feature-icon to-animate">
              <i class="icon-microphone"></i>
            </div>
            <div class="fh5co-feature-text">
              <h3>Voice Recording</h3>
              <p>Far far away, behind the word mountains, far from the countries Vokalia.</p>
              <p><a href="#">Read more</a></p>
            </div>
          </div>
          <div class="fh5co-feature no-border">
            <div class="fh5co-feature-icon to-animate">
              <i class="icon-clock2"></i>
            </div>
            <div class="fh5co-feature-text">
              <h3>24/7 Support</h3>
              <p>Far far away, behind the word mountains, far from the countries Vokalia.</p>
              <p><a href="#">Read more</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Features -->


  <div class="fh5co-spacer fh5co-spacer-lg"></div>
  <!-- Products -->
  <div class="container" id="fh5co-products">
    <div class="row text-left">
      <div class="col-md-8">
        <h2 class="fh5co-section-lead">Products</h2>
        <h3 class="fh5co-section-sub-lead">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</h3>
      </div>
      <div class="fh5co-spacer fh5co-spacer-md"></div>
    </div>
    <div class="row">
      <div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 fh5co-mb30">
        <div class="fh5co-product">
          <img src="assets/slide_1.jpg" alt="FREEHTML5.co Free HTML5 Template Bootstrap" class="img-responsive img-rounded to-animate">
          <h4>Lorem ipsum</h4>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          <p><a href="#">Read more</a></p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 fh5co-mb30">
        <div class="fh5co-product">
          <img src="assets/slide_2.jpg" alt="FREEHTML5.co Free HTML5 Template Bootstrap" class="img-responsive img-rounded to-animate">
          <h4>Architecto nihil</h4>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          <p><a href="#">Read more</a></p>
        </div>
      </div>
      <div class="visible-sm-block visible-xs-block clearfix"></div>
      <div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 fh5co-mb30">
        <div class="fh5co-product">
          <img src="assets/slide_3.jpg" alt="FREEHTML5.co Free HTML5 Template Bootstrap" class="img-responsive img-rounded to-animate">
          <h4>Animi earum</h4>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          <p><a href="#">Read more</a></p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 fh5co-mb30">
        <div class="fh5co-product">
          <img src="assets/slide_4.jpg" alt="FREEHTML5.co Free HTML5 Template Bootstrap" class="img-responsive img-rounded to-animate">
          <h4>Recusandae iste</h4>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          <p><a href="#">Read more</a></p>
        </div>
      </div>

    </div>
  </div>
  <!-- Products -->
  <div class="fh5co-spacer fh5co-spacer-lg"></div>

  <div id="fh5co-clients">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 fh5co-client-logo text-center to-animate"><img src="assets/client_1.png" alt="FREEHTML5.co Free HTML5 Bootstrap Template" class="img-responsive"></div>
        <div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 fh5co-client-logo text-center to-animate"><img src="assets/client_2.png" alt="FREEHTML5.co Free HTML5 Bootstrap Template" class="img-responsive"></div>
        <div class="visible-sm-block visible-xs-block clearfix"></div>
        <div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 fh5co-client-logo text-center to-animate"><img src="assets/client_3.png" alt="FREEHTML5.co Free HTML5 Bootstrap Template" class="img-responsive"></div>
        <div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 fh5co-client-logo text-center to-animate"><img src="assets/client_4.png" alt="FREEHTML5.co Free HTML5 Bootstrap Template" class="img-responsive"></div>
      </div>
    </div>
  </div>

  <div class="fh5co-bg-section" style="background-image: url(assets/slide_2.jpg); background-attachment: fixed;">
    <div class="fh5co-overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="fh5co-hero-wrap">
            <div class="fh5co-hero-intro text-center">
              <h1 class="fh5co-lead"><span class="quo">&ldquo;</span>Design is not just what it looks like and feels like. Design is how it works. <span class="quo">&rdquo;</span></h1>
              <p class="author">&mdash; <cite>Steve Jobs</cite></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>